/**
 * Elite BoB Tech Vault — 45 level-4 exercises (never served to L1–L3 generator).
 */

import type { Exercise } from "./cali_library.tsx";

type EliteEx = Exercise & { description: string };

function e(
  id: string,
  name: string,
  track: "static" | "ascension" | "dynamic" | "flow",
  category: Exercise["category"],
  pattern: Exercise["pattern"],
  metric: Exercise["metric"],
  dose: Exercise["defaultDose"],
  difficulty: number,
  equipment: Exercise["equipment"],
  description: string,
  cues: string[],
  extra?: Partial<Exercise>,
): EliteEx {
  return {
    id,
    name,
    category,
    pattern,
    level: 4,
    eliteTrack: track,
    difficulty,
    equipment,
    unilateral: extra?.unilateral ?? false,
    metric,
    defaultDose: dose,
    cues,
    description,
    tempoHint: extra?.tempoHint,
    scalingDown: extra?.scalingDown,
    scalingUp: extra?.scalingUp,
  };
}

export const ELITE_EXERCISES: ReadonlyArray<EliteEx> = Object.freeze([
  // ── STATIC POWER (10) ──────────────────────────────────────────────────
  e("elite_strict_front_lever", "Strict Front Lever", "static", "pull", "iso_hold", "time_sec",
    [4, 8, 3, 8], 9, "bar",
    "From dead hang, raise a straight body horizontal (face down, back up). Arms locked, scapula retracted, core and legs tight. BoB strength category: 3s clean hold wins.",
    ["Dead hang start — no swing", "Retract scapula before you lift", "Lock knees and point toes — one rigid line"],
    { scalingDown: "pull_tuck_front_lever_row", scalingUp: "elite_weighted_static" }),
  e("elite_full_back_lever", "Full Back Lever", "static", "pull", "iso_hold", "time_sec",
    [4, 8, 3, 8], 9, "bar",
    "Inverted hang, body horizontal face down, arms straight, chest open, full body tension. Shoulder and core intensive — battle judges reward clean 3s+.",
    ["Open chest — don't collapse forward", "Straight arms, active shoulders", "Squeeze glutes to keep hips level"],
    { scalingDown: "pull_tuck_front_lever_row" }),
  e("elite_human_flag", "Human Flag", "static", "core", "iso_hold", "time_sec",
    [4, 8, 3, 6], 10, "bar",
    "Sideways on vertical bar or pole, body horizontal, one arm pulling one pushing, full side tension. Iconic flair move that steals crowd energy.",
    ["Top arm pulls, bottom arm pushes", "Stack shoulders over the bar", "Lock the obliques — no banana bend"],
    { scalingDown: "core_side_plank" }),
  e("elite_straddle_planche", "Straddle Planche", "static", "push", "iso_hold", "time_sec",
    [4, 8, 3, 8], 10, "bar",
    "On bars or parallettes, body horizontal prone, legs wide straddle, straight arms, scap protraction. Chest and shoulder beast for static battles.",
    ["Protract hard — push the floor away", "Straddle wide to shorten lever", "Depress shoulders — no shrug"],
    { scalingDown: "push_pike" }),
  e("elite_full_planche", "Full Planche", "static", "push", "iso_hold", "time_sec",
    [4, 8, 3, 6], 10, "bar",
    "Same as straddle planche but legs together straight. Pure straight-arm strength — one of the hardest statics in BoB.",
    ["Legs glued, toes pointed", "Lean forward until float is real", "Wrists stacked under shoulders"],
    { scalingDown: "elite_straddle_planche" }),
  e("elite_victorian_cross", "Victorian Cross", "static", "pull", "iso_hold", "time_sec",
    [3, 6, 3, 6], 10, "bar",
    "Advanced front-lever variant on forearms or high bar, body arched high horizontal. Extreme shoulder and core demand.",
    ["Forearms or high bar — pick your line", "Arch the chest up, not the lower back", "Short holds — quality over ego"],
    { scalingDown: "elite_strict_front_lever" }),
  e("elite_maltese", "Maltese", "static", "push", "iso_hold", "time_sec",
    [3, 6, 3, 5], 10, "bar",
    "Low planche-style hold between bars, body near ground, arms wide. One of the hardest statics — elite vault territory only.",
    ["Wide arm placement", "Lean deep — near horizontal", "Micro-holds count in training"],
    { scalingDown: "elite_straddle_planche" }),
  e("elite_v_sit_manna", "V-Sit / Manna", "static", "core", "iso_hold", "time_sec",
    [4, 8, 3, 10], 9, "bar",
    "In support on bars, lift straight legs vertical or diagonal, push shoulders down hard. Hip-flexor and core destroyer.",
    ["Shoulders down and depressed", "Legs straight — no knee bend", "Compress before you lift"],
    { scalingDown: "core_l_sit" }),
  e("elite_dragon_flag", "Dragon Flag", "static", "core", "iso_hold", "time_sec",
    [4, 8, 3, 8], 9, "none",
    "Supine hold — grab behind head, body straight off floor with only upper back touching. Legendary Bruce Lee core move.",
    ["Only upper back touches bench", "One rigid line head to heels", "Lower slow — don't collapse"],
    { scalingDown: "core_hollow_hold" }),
  e("elite_strict_handstand_press", "Strict Handstand Press", "static", "push", "vertical_push", "reps",
    [3, 6, 1, 3], 9, "none",
    "From support or floor, press to full handstand on bars with control. Balance plus pressing power for transition battles.",
    ["No kick — pure press", "Stack before you drive", "Lock out at the top"],
    { scalingDown: "push_pike" }),

  // ── ASCENSION / MU VARIANTS (5) ────────────────────────────────────────
  e("elite_dead_hang_mu", "Strict Dead Hang Muscle-Up", "ascension", "pull", "vertical_pull", "reps",
    [4, 8, 1, 3], 9, "bar",
    "Full hang, no kip or swing, explosive pull over bar to support. Pure strength standard for BoB ascension scoring.",
    ["Zero swing — dead start", "Pull bar to hips then transition", "Finish in solid support"],
    { scalingDown: "pull_archer_pullup" }),
  e("elite_360_mu", "360 Muscle-Up", "ascension", "pull", "vertical_pull", "reps",
    [3, 6, 1, 2], 10, "bar",
    "Muscle-up plus full body rotation plus regrab in one fluid motion. Transition power that wins creativity points.",
    ["Commit to rotation at the top", "Eyes spot the bar for regrab", "One breath, one motion"]),
  e("elite_hefesto", "Ring / Bar Hefesto", "ascension", "pull", "vertical_pull", "reps",
    [3, 6, 1, 2], 10, "bar",
    "From skin-the-cat inverted hang, reverse pull supinated grip up to top support. Shoulder mobility king.",
    ["Skin-the-cat entry controlled", "Supinated grip on the pull", "Finish high in support"],
    { scalingDown: "elite_skin_the_cat_german_hang" }),
  e("elite_skin_the_cat_german_hang", "Skin the Cat + German Hang", "ascension", "pull", "vertical_pull", "reps",
    [3, 6, 2, 5], 8, "bar",
    "Full shoulder rotation pass-through to inverted hang hold. Mobility foundation for levers and flips.",
    ["Slow rotation — own each degree", "Pause in German hang", "Exit with control"],
    { scalingDown: "mob_german_hang_negative" }),
  e("elite_pullover", "Pullover", "ascension", "pull", "vertical_pull", "reps",
    [4, 8, 2, 5], 7, "bar",
    "Swing or strict pull body over bar to support — classic mount. Builds to advanced combos.",
    ["Hip drive only if strict isn't ready", "Bar clears the hips", "Land in support, not collapse"],
    { scalingDown: "pull_archer_pullup" }),

  // ── DYNAMIC POWER / SPINS (13) ─────────────────────────────────────────
  e("elite_swing_360", "Swing 360", "dynamic", "conditioning", "dynamic_spin", "reps",
    [4, 8, 1, 3], 8, "bar",
    "Explosive swing forward, full 360° rotation plus regrab same grip. Rotation category crowd pleaser.",
    ["Build amplitude first", "Tuck tight through rotation", "Regrab same grip — no slip"]),
  e("elite_swing_540", "Swing 540", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 2], 9, "bar",
    "1.5 rotations in air during swing regrab. Step up from 360 — demands more height and timing.",
    ["Extra hip drive at release", "Spot the bar early", "Absorb catch with bent arms then lock"]),
  e("elite_swing_720", "Swing 720", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 5, 1, 2], 10, "bar",
    "Double full rotation — elite dynamic. Requires massive swing and fearless commitment.",
    ["Max amplitude — patient build", "Tight tuck, fast spin", "Regrab is the whole battle"]),
  e("elite_swing_900", "Swing 900", "dynamic", "conditioning", "dynamic_spin", "reps",
    [2, 4, 1, 1], 10, "bar",
    "2.5 rotations — god-tier dynamic. Training attempts only with full spot and fresh grip.",
    ["Only when 720 is consistent", "Film every attempt", "Bail plan before you swing"]),
  e("elite_geinger", "Geinger", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 2], 9, "bar",
    "Giant swing backflip twist plus regrab — classic power move from gymnastics bar culture.",
    ["Giant first — own the circle", "Flip then twist — sequence matters", "Catch high on the bar"]),
  e("elite_frisbee_flip", "Frisbee / Side Flip", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 2], 8, "bar",
    "Lateral body flip with side rotation from backswing plus regrab. Style points in BoB freestyle.",
    ["Lateral set — not forward", "Spot the bar through rotation", "Soft catch, hard lockout"]),
  e("elite_switchblade", "Switchblade", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 3], 8, "bar",
    "180° twist plus barhop or leg switch in dynamic flow. Links static and dynamic in one beat.",
    ["Twist at peak of swing", "Leg switch is crisp — no drift", "Flow into next skill"]),
  e("elite_shrimp_flip", "Shrimp Flip", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 3], 8, "bar",
    "Legs and body shrimp-style flip between arms during swing. Compact rotation — sneaky crowd pop.",
    ["Tuck knees to chest mid-air", "Hands stay close to bar", "Regrab immediately"]),
  e("elite_front_flip_regrab", "Front Flip Regrab", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 2], 8, "bar",
    "Forward somersault from swing plus catch bar. Foundation flip for alley-oop progressions.",
    ["Commit forward — no half flip", "Eyes open for bar", "Catch with both hands"]),
  e("elite_alley_oop", "Alley-Oop", "dynamic", "conditioning", "dynamic_spin", "reps",
    [2, 5, 1, 2], 9, "bar",
    "Backward over-the-bar throw from swing momentum. High risk, high reward BoB moment.",
    ["Massive swing first", "Release at the right apex", "Spot behind you for catch"]),
  e("elite_giants", "Giants", "dynamic", "conditioning", "locomotion", "reps",
    [4, 8, 2, 5], 7, "bar",
    "Full giant circle swings forward and back with straight body. Builds amplitude for all spins.",
    ["Hollow body through the bottom", "Push down at the top", "Rhythm before tricks"]),
  e("elite_airwalk", "Airwalk", "dynamic", "conditioning", "locomotion", "reps",
    [3, 6, 2, 4], 7, "bar",
    "Stylized leg walking motion in air during dynamic swings or holds. Showmanship plus control.",
    ["Big swing — legs walk at peak", "Stay tight through core", "Land the style — no floppy feet"]),
  e("elite_tornado_grip_spin", "Tornado / Grip Change Spins", "dynamic", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 3], 9, "bar",
    "Multiple grip flips plus rotation combos in swing. Advanced hand choreography.",
    ["One grip change at a time first", "Chalk fresh every block", "Rotation follows grip — not before"]),

  // ── TRANSITIONS / COMBOS / FLOWS (17) ───────────────────────────────────
  e("elite_pbar_flow", "P-Bar Flow", "flow", "push", "combo_flow", "reps",
    [3, 6, 1, 3], 9, "bar",
    "Seamless parallel bar sequence: dips → L-sit → planche press → transfers. Creativity and control category.",
    ["Link skills without pause", "Own each position 1s minimum", "Exit as clean as entry"],
    { scalingDown: "push_dip_parallel" }),
  e("elite_barhop_180", "Barhop 180 / Combo Transfers", "flow", "conditioning", "combo_flow", "reps",
    [3, 6, 2, 5], 8, "bar",
    "Hop over bar with twist or switch sides fluidly. Transition speed wins BoB flow rounds.",
    ["Explode from support", "Twist eyes-first", "Land soft, re-grip fast"]),
  e("elite_fl_raise_pull", "Front Lever Raise + Pull", "flow", "pull", "combo_flow", "reps",
    [3, 6, 2, 4], 9, "bar",
    "From hang to front lever then pull-ups in lever position. Static meets strength endurance.",
    ["Raise to lever first — no swing", "Pull only if lever is honest", "Reset hang between reps"]),
  e("elite_bl_skin_cat_exit", "Back Lever to Skin-the-Cat Exit", "flow", "pull", "combo_flow", "reps",
    [3, 6, 1, 3], 9, "bar",
    "Hold back lever then controlled exit through skin-the-cat rotation. Shows shoulder mastery.",
    ["3s lever before exit", "Rotate slow through German hang", "Finish in hang — no dump"]),
  e("elite_archer_pullup", "One-Arm Archer Pull-Ups", "flow", "pull", "horizontal_pull", "reps",
    [4, 8, 2, 5], 8, "bar",
    "Unilateral pulling in dynamic or static setups. Builds toward one-arm battle attempts.",
    ["Top arm straight — arrow shape", "Pull with the working side", "Control the descent"],
    { scalingDown: "pull_archer_pullup" }),
  e("elite_korean_dips", "Korean Dips / Straight-Bar Dips", "flow", "push", "vertical_push", "reps",
    [4, 8, 3, 6], 8, "bar",
    "Extreme range dips on single bar — wrist heavy. BoB push endurance test.",
    ["Lean forward at bottom", "Wrists warm — don't rush depth", "Lock out every rep"]),
  e("elite_elbow_lever_press", "Elbow Lever to Press", "flow", "push", "combo_flow", "reps",
    [3, 6, 1, 3], 9, "bar",
    "Transition from elbow balance to handstand press. Rare flow that judges remember.",
    ["Stable elbow lever first", "Shift weight to hands slowly", "Press only when stacked"]),
  e("elite_toes_to_bar_adv", "Toes-to-Bar Advanced", "flow", "core", "flexion", "reps",
    [4, 8, 3, 8], 8, "bar",
    "Explosive toes-to-bar plus windshield wiper legs in hang. Core power for dynamic exits.",
    ["Strict T2B before wipers", "Control the swing — no kip cheat", "Wipers slow and parallel"]),
  e("elite_dragon_pistol_flow", "Dragon Squat / Pistol Flow", "flow", "legs", "combo_flow", "reps",
    [3, 6, 2, 5], 8, "none",
    "Leg work integrated into floor and bar transitions — full game coverage.",
    ["Own single-leg balance first", "Link squat to next skill smoothly", "Alternate legs each set"]),
  e("elite_mu_lever_spin_combo", "Combo: MU → Lever → Spin", "flow", "pull", "combo_flow", "reps",
    [2, 4, 1, 2], 10, "bar",
    "Muscle-up straight into front lever hold then explosive spin exit. Signature BoB chain.",
    ["MU clean to support", "Drop to lever — 3s minimum", "Spin only from stable lever"]),
  e("elite_floor_parallettes", "Floor Game + Parallettes", "flow", "push", "combo_flow", "reps",
    [3, 6, 1, 3], 8, "bar",
    "Integrate pistol, dragon squats, handstand presses, strong floor sequences on parallettes.",
    ["Floor skills match bar intensity", "Press to handstand between sets", "No dead time in flow"]),
  e("elite_dislocation_720", "Dislocation 720 / Advanced Regrabs", "flow", "pull", "dynamic_spin", "reps",
    [2, 4, 1, 1], 10, "bar",
    "Extreme shoulder pass plus double spin regrab — seen in top battles only.",
    ["Shoulders fully warm", "Spotter or thick mat", "One progression step per month"]),
  e("elite_supra_dragon_planche", "Supra / Dragon Planche", "flow", "push", "combo_flow", "reps",
    [2, 4, 1, 2], 10, "bar",
    "Dynamic planche entry or dragon-flavored planche hold in flow. Peak pressing artistry.",
    ["Build from planche leans", "Dragon entry — hips drive first", "Hold 2s or it doesn't count"]),
  e("elite_cast_flip_dismount", "Cast Flip / Screw Dismounts", "flow", "conditioning", "dynamic_spin", "reps",
    [3, 6, 1, 2], 8, "bar",
    "Gymnastics-style cast to flip or dismount with twist. Battle-ending flair.",
    ["Cast to horizontal first", "Flip at peak cast", "Stick landing or roll out"]),
  e("elite_weighted_static", "Weighted Static Holds", "flow", "pull", "iso_hold", "time_sec",
    [3, 6, 3, 8], 10, "bar",
    "Any lever, planche, or flag plus added weight for pro strength. Use micro-loads only.",
    ["Light weight — perfect form", "Same hold rules: 3s clean", "Log weight in session notes"],
    { scalingDown: "elite_strict_front_lever" }),
  e("elite_one_arm_variations", "One-Arm Variations", "flow", "pull", "combo_flow", "reps",
    [2, 5, 1, 2], 10, "bar",
    "One-arm MU, flag, or lever attempts in battle context. Attempt training with full spot.",
    ["Assist band or finger spot", "Record every attempt", "Quality over volume"]),
  e("elite_freestyle_combo", "Full Freestyle Combo Flow", "flow", "conditioning", "combo_flow", "time_sec",
    [2, 4, 30, 60], 10, "bar",
    "30–60s seamless chain: MU + lever + 720 spin + p-bar transfer + creative dismount. Creativity and endurance winner.",
    ["Plan 5 skills max per chain", "Breathe at holds — don't rush", "End on your hardest move"]),
]);