/**
 * BOTB Calisthenics — Curated Exercise Library
 * =============================================
 *
 * Pure data, server-owned, versioned. The generator (cali.tsx, future slice)
 * selects from this list using a seeded RNG. A workout's `libraryVersion`
 * field is stored alongside its `seed` so the same workout can be
 * deterministically re-rendered later for auditing / anchor verification.
 *
 * VERSIONING RULES:
 *   - Bump LIBRARY_VERSION whenever any exercise is added, removed, OR has
 *     its `id`, `metric`, or `defaultDose` change. Pure cue/cosmetic edits
 *     do NOT require a bump (they don't affect reproducibility).
 *   - Never reuse an `id`. Deleted exercises stay removed; new variants get
 *     new ids. This protects historical workouts from silent drift.
 *
 * `level` is the MINIMUM workout level the exercise may appear in.
 *   L1 sessions select only L1 exercises.
 *   L2 sessions may select L1 or L2.
 *   L3 sessions may select any.
 *
 * `difficulty` (1..10) is a fine-grained selection weight WITHIN a level.
 *   The generator targets a difficulty band per block per level — e.g. an L1
 *   primary-push block targets difficulty 2-4, an L3 primary-push targets 6-9.
 *
 * `equipment` enumerates everything required. The generator filters by
 *   subset of the user's available-equipment profile field.
 *
 * NO PII, NO MEDIA URLS, NO USER DATA HERE. This file is loaded into every
 * edge isolate at boot — keep it lean.
 */

export const LIBRARY_VERSION = "cali-lib-1.2.0";

export type CaliCategory =
  | "push"
  | "pull"
  | "core"
  | "legs"
  | "conditioning"
  | "mobility";

export type CaliPattern =
  | "horizontal_push"
  | "vertical_push"
  | "horizontal_pull"
  | "vertical_pull"
  | "squat"
  | "lunge"
  | "hinge"
  | "anti_extension"
  | "anti_rotation"
  | "flexion"
  | "iso_hold"
  | "locomotion"
  | "plyo"
  | "stretch";

export type CaliMetric = "reps" | "time_sec";
export type CaliEquipmentReq = "none" | "bar" | "rings" | "wall";

export interface Exercise {
  id: string;
  name: string;
  category: CaliCategory;
  pattern: CaliPattern;
  /** Minimum workout level this exercise can appear in (1-3) */
  level: 1 | 2 | 3;
  /** Difficulty rating 1-10 — used for in-level selection weighting */
  difficulty: number;
  equipment: CaliEquipmentReq;
  unilateral: boolean;
  metric: CaliMetric;
  /**
   * Hint range the generator may use as a starting dose for this exercise.
   * The generator can override per block template (e.g. L3 push block bumps
   * the upper rep bound). [setsMin, setsMax, repsOrTimeMin, repsOrTimeMax].
   */
  defaultDose: [number, number, number, number];
  tempoHint?: string;
  /** 1-3 short coaching cues, < 80 chars each */
  cues: string[];
  /** Optional scaling references — generator does not auto-scale yet */
  scalingDown?: string;
  scalingUp?: string;
}

// ---------------------------------------------------------------------------
// PUSH (13)
// ---------------------------------------------------------------------------

const PUSH: Exercise[] = [
  {
    id: "push_wall",
    name: "Wall Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 1,
    equipment: "wall",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 3, 8, 15],
    cues: ["Hands at chest height", "Body straight from heels to head", "Touch the wall with your chest"],
    scalingUp: "push_incline",
  },
  {
    id: "push_incline",
    name: "Incline Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Hands on a bench or sturdy surface", "Brace your core — no sagging hips", "Lower under control"],
    scalingDown: "push_wall",
    scalingUp: "push_knee",
  },
  {
    id: "push_knee",
    name: "Knee Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Knees down, body straight from knees to head", "Elbows ~45° from torso", "Chest to the floor"],
    scalingUp: "push_standard",
  },
  {
    id: "push_standard",
    name: "Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 5, 15],
    tempoHint: "2-1-1-1",
    cues: ["Hands under shoulders", "Squeeze glutes, brace abs", "Full lockout at the top"],
    scalingDown: "push_knee",
    scalingUp: "push_diamond",
  },
  {
    id: "push_wide",
    name: "Wide-Grip Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Hands ~1.5× shoulder width", "Elbows flare slightly", "Chest leads on the descent"],
  },
  {
    id: "push_diamond",
    name: "Diamond Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 5, 12],
    cues: ["Index fingers + thumbs touch", "Elbows track close to ribs", "Triceps do the work"],
    scalingDown: "push_standard",
  },
  {
    id: "push_archer",
    name: "Archer Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 3, 8],
    cues: ["One arm bends, the other stays straight", "Shift weight side to side", "Reps per side"],
    scalingUp: "push_oa_negative",
  },
  {
    id: "push_decline",
    name: "Decline Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 6, 12],
    cues: ["Feet elevated on a bench/step", "More load on shoulders + upper chest", "Don't let hips pike up"],
  },
  {
    id: "push_pseudo_planche",
    name: "Pseudo Planche Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 4, 10],
    cues: ["Hands by hips, fingers pointing back", "Lean forward — weight shifts onto wrists", "Tight protraction at top"],
  },
  {
    id: "push_pike",
    name: "Pike Push-Up",
    category: "push",
    pattern: "vertical_push",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 5, 12],
    cues: ["Hips high, body in an inverted V", "Lower the crown of your head between hands", "Drive straight up"],
    scalingUp: "push_handstand_wall",
  },
  {
    id: "push_oa_negative",
    name: "One-Arm Push-Up Negative",
    category: "push",
    pattern: "horizontal_push",
    level: 3,
    difficulty: 8,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 5, 3, 6],
    tempoHint: "5-0-X-0 (5s descent)",
    cues: ["Feet wide for stability", "Lower 5 seconds, push back up with both hands", "Reps per side"],
  },
  {
    id: "push_oa",
    name: "One-Arm Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 3,
    difficulty: 10,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 5, 2, 6],
    cues: ["Feet wide, free hand on hip or behind back", "Resist rotating the hips", "Reps per side"],
  },
  {
    id: "push_handstand_wall",
    name: "Wall Handstand Push-Up",
    category: "push",
    pattern: "vertical_push",
    level: 3,
    difficulty: 9,
    equipment: "wall",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 3, 8],
    cues: ["Kick up to a stable wall handstand", "Lower until head lightly taps the floor", "Press to full lockout"],
  },
  {
    id: "push_close_grip",
    name: "Close-Grip Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 5, 12],
    cues: ["Hands inside shoulder width", "Elbows hug the ribs", "Triceps drive the press"],
  },
  {
    id: "push_tempo_3010",
    name: "Tempo Push-Up (3-0-1-0)",
    category: "push",
    pattern: "horizontal_push",
    level: 1,
    difficulty: 5,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 5, 10],
    tempoHint: "3-0-1-0",
    cues: ["3-second descent", "No pause at the bottom", "Drive up in 1 count"],
  },
  {
    id: "push_hindu",
    name: "Hindu Push-Up",
    category: "push",
    pattern: "horizontal_push",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Start in pike, dive down and forward", "Press up to upward dog", "Reverse the motion fluidly"],
  },
  {
    id: "push_clap",
    name: "Clap Push-Up",
    category: "push",
    pattern: "plyo",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 4, 8],
    cues: ["Explode off the floor", "Clap quickly under the chest", "Land soft into the next rep"],
  },
  {
    id: "push_dip_bench",
    name: "Bench Dip",
    category: "push",
    pattern: "vertical_push",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Hands on a bench behind you, feet on the floor", "Elbows track straight back", "Lower until upper arms are parallel"],
  },
  {
    id: "push_dip_parallel",
    name: "Parallel Bar Dip",
    category: "push",
    pattern: "vertical_push",
    level: 2,
    difficulty: 7,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 4, 12],
    cues: ["Support on parallel bars, lean slightly forward for chest emphasis", "Lower until shoulders pass elbows", "Full lockout at the top"],
  },
  {
    id: "push_ring_dip",
    name: "Ring Dip",
    category: "push",
    pattern: "vertical_push",
    level: 3,
    difficulty: 8,
    equipment: "rings",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 3, 10],
    cues: ["Rings turned out at the top", "Resist wobble — slow controlled descent", "Hollow body throughout"],
  },
  {
    id: "push_pseudo_negative",
    name: "Pseudo Planche Negative",
    category: "push",
    pattern: "horizontal_push",
    level: 3,
    difficulty: 8,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 3, 6],
    tempoHint: "5s descent",
    cues: ["Heavy forward lean, fingers pointed back", "Lower 5 seconds with locked elbows-out arms", "Push back up however you can"],
  },
];

// ---------------------------------------------------------------------------
// PULL (11)
// ---------------------------------------------------------------------------

const PULL: Exercise[] = [
  {
    id: "pull_doorway_row",
    name: "Doorway Row",
    category: "pull",
    pattern: "horizontal_pull",
    level: 1,
    difficulty: 1,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 3, 8, 15],
    cues: ["Grip both sides of a sturdy doorframe", "Lean back, feet stay planted", "Squeeze shoulder blades together"],
  },
  {
    id: "pull_table_row",
    name: "Table Row",
    category: "pull",
    pattern: "horizontal_pull",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Lie under a sturdy table, grip the edge", "Body straight, heels on floor", "Pull chest to the underside"],
  },
  {
    id: "pull_inverted_row",
    name: "Inverted Row",
    category: "pull",
    pattern: "horizontal_pull",
    level: 2,
    difficulty: 5,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 5, 12],
    cues: ["Bar at hip height", "Body rigid plank, chest to bar", "Pause at the top"],
  },
  {
    id: "pull_pullup_negative",
    name: "Negative Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 2,
    difficulty: 6,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 3, 8],
    tempoHint: "5-0-X-0",
    cues: ["Jump or step to the top of a pull-up", "Lower under control for 5 seconds", "Full hang each rep"],
    scalingUp: "pull_pullup",
  },
  {
    id: "pull_assisted_pullup",
    name: "Band-Assisted Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 2,
    difficulty: 5,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 4, 10],
    cues: ["Loop a resistance band over the bar, foot in the loop", "Full extension at the bottom", "Chin clears the bar"],
    scalingUp: "pull_pullup",
  },
  {
    id: "pull_pullup",
    name: "Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 2,
    difficulty: 7,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 3, 10],
    cues: ["Overhand grip, shoulder-width", "Initiate with shoulder blades", "Chin over bar, full hang at bottom"],
  },
  {
    id: "pull_chinup",
    name: "Chin-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 2,
    difficulty: 6,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 3, 10],
    cues: ["Underhand grip, shoulder-width", "Drive elbows down to the floor", "Pause at top, control descent"],
  },
  {
    id: "pull_wide_pullup",
    name: "Wide-Grip Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 8,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 3, 8],
    cues: ["Grip ~1.5× shoulder width", "Pull chest up toward the bar", "Lats lead, biceps assist"],
  },
  {
    id: "pull_archer_pullup",
    name: "Archer Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 9,
    equipment: "bar",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 2, 6],
    cues: ["Wide grip — pull to one side", "Working arm bends, free arm stays extended", "Reps per side"],
  },
  {
    id: "pull_typewriter",
    name: "Typewriter Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 9,
    equipment: "bar",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 2, 5],
    cues: ["Pull up wide, shift across the bar at the top", "Slow, controlled lateral travel", "Reps = full passes"],
  },
  {
    id: "pull_muscle_up",
    name: "Muscle-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 10,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 1, 5],
    cues: ["False grip helps", "Pull explosively, transition early", "Lock out on top — no kipping"],
  },
  {
    id: "pull_scap_pullup",
    name: "Scapular Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 1,
    difficulty: 3,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 5, 12],
    cues: ["Dead hang", "Pull shoulder blades down + back — no elbow bend", "Pause 1 second at the top"],
  },
  {
    id: "pull_active_hang",
    name: "Active Hang",
    category: "pull",
    pattern: "iso_hold",
    level: 1,
    difficulty: 3,
    equipment: "bar",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [3, 4, 15, 40],
    cues: ["Hang with scapulae depressed (not shrugged)", "Squeeze lats, ribs down", "Slow exhale"],
  },
  {
    id: "pull_inverted_row_feet_up",
    name: "Feet-Elevated Inverted Row",
    category: "pull",
    pattern: "horizontal_pull",
    level: 2,
    difficulty: 6,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 5, 5, 12],
    cues: ["Feet on a bench, body straight", "Chest meets the bar", "No swinging — full control"],
  },
  {
    id: "pull_archer_row",
    name: "Archer Row",
    category: "pull",
    pattern: "horizontal_pull",
    level: 2,
    difficulty: 7,
    equipment: "bar",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 4, 8],
    cues: ["Pull primarily with one arm, the other extended", "No hip rotation", "Reps per side"],
  },
  {
    id: "pull_commando",
    name: "Commando Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 8,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 4, 8],
    cues: ["Mixed grip — sideways on the bar", "Pull head past one side, then the other", "1 rep = both sides"],
  },
  {
    id: "pull_high_pullup",
    name: "High Pull-Up (Sternum)",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 9,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 2, 6],
    cues: ["Pull until sternum meets the bar", "Lean back slightly at the top", "Lats max contracted"],
  },
  {
    id: "pull_tuck_front_lever_row",
    name: "Tuck Front Lever Row",
    category: "pull",
    pattern: "horizontal_pull",
    level: 3,
    difficulty: 9,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 3, 8],
    cues: ["Tuck position — pull chest to bar with body horizontal", "Lats + core fire together", "Hollow body throughout"],
  },
  {
    id: "pull_l_sit_pullup",
    name: "L-Sit Pull-Up",
    category: "pull",
    pattern: "vertical_pull",
    level: 3,
    difficulty: 9,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 2, 6],
    cues: ["Hold legs horizontal the entire set", "Pull chin over bar", "No leg swing"],
  },
];

// ---------------------------------------------------------------------------
// CORE (13)
// ---------------------------------------------------------------------------

const CORE: Exercise[] = [
  {
    id: "core_dead_bug",
    name: "Dead Bug",
    category: "core",
    pattern: "anti_extension",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 3, 6, 12],
    cues: ["Lower back pressed into the floor", "Opposite arm + leg extend slowly", "Reps per side"],
  },
  {
    id: "core_bird_dog",
    name: "Bird Dog",
    category: "core",
    pattern: "anti_rotation",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 3, 6, 12],
    cues: ["Quadruped — neutral spine", "Opposite arm + leg reach long, pause", "No twisting in the hips"],
  },
  {
    id: "core_plank",
    name: "Plank",
    category: "core",
    pattern: "iso_hold",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [3, 3, 20, 60],
    cues: ["Elbows under shoulders", "Glutes + abs braced — no sag", "Look at your hands"],
  },
  {
    id: "core_side_plank",
    name: "Side Plank",
    category: "core",
    pattern: "iso_hold",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: true,
    metric: "time_sec",
    defaultDose: [3, 3, 15, 45],
    cues: ["Stack feet, elbow under shoulder", "Hips lifted, straight line", "Time per side"],
  },
  {
    id: "core_crunch",
    name: "Crunch",
    category: "core",
    pattern: "flexion",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 3, 10, 20],
    cues: ["Lift shoulder blades off the floor", "Ribs to hips, exhale up", "Don't yank the neck"],
  },
  {
    id: "core_bicycle_crunch",
    name: "Bicycle Crunch",
    category: "core",
    pattern: "flexion",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 3, 10, 20],
    cues: ["Opposite elbow to opposite knee", "Slow, controlled — no momentum", "Reps total (both sides)"],
  },
  {
    id: "core_leg_raise_lying",
    name: "Lying Leg Raise",
    category: "core",
    pattern: "flexion",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Lower back glued to the floor", "Legs straight, lift to vertical", "Slow down on the descent"],
  },
  {
    id: "core_hollow_hold",
    name: "Hollow Body Hold",
    category: "core",
    pattern: "iso_hold",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [3, 4, 15, 40],
    cues: ["Lower back pressed flat", "Arms and legs lifted — body in a banana shape", "Breathe shallowly through the diaphragm"],
  },
  {
    id: "core_v_up",
    name: "V-Up",
    category: "core",
    pattern: "flexion",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Arms and legs lift simultaneously", "Touch hands to feet at the top", "Lower with control"],
  },
  {
    id: "core_hanging_knee_raise",
    name: "Hanging Knee Raise",
    category: "core",
    pattern: "flexion",
    level: 2,
    difficulty: 6,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 5, 12],
    cues: ["Dead hang, scapulae active", "Knees to chest, no swinging", "Lower under control"],
    scalingUp: "core_hanging_leg_raise",
  },
  {
    id: "core_hanging_leg_raise",
    name: "Hanging Leg Raise",
    category: "core",
    pattern: "flexion",
    level: 3,
    difficulty: 8,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 4, 10],
    cues: ["Straight legs, raise to horizontal or higher", "Posterior pelvic tilt at the top", "No kipping"],
  },
  {
    id: "core_dragon_flag_negative",
    name: "Dragon Flag Negative",
    category: "core",
    pattern: "anti_extension",
    level: 3,
    difficulty: 9,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 3, 6],
    tempoHint: "5s descent",
    cues: ["Anchor your hands behind your head", "Body straight, lower in one piece", "Don't break at the hips"],
  },
  {
    id: "core_l_sit",
    name: "L-Sit Hold",
    category: "core",
    pattern: "iso_hold",
    level: 3,
    difficulty: 8,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [3, 5, 8, 25],
    cues: ["Hands on floor or parallettes — press down hard", "Legs straight, parallel to the ground", "Push the floor away"],
  },
  {
    id: "core_glute_bridge_iso",
    name: "Glute Bridge Hold",
    category: "core",
    pattern: "iso_hold",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 20, 45],
    cues: ["Heels close to glutes", "Drive hips up — squeeze glutes hard", "Ribs down, neutral spine"],
  },
  {
    id: "core_hollow_rock",
    name: "Hollow Rock",
    category: "core",
    pattern: "anti_extension",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 8, 20],
    cues: ["Hollow body shape — no gap behind lower back", "Rock head-to-toe like a banana", "Keep arms and legs locked"],
  },
  {
    id: "core_russian_twist",
    name: "Russian Twist",
    category: "core",
    pattern: "anti_rotation",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 3, 10, 24],
    cues: ["Seated, lean back, feet hovering", "Rotate side to side under control", "Reps = total touches"],
  },
  {
    id: "core_copenhagen_plank",
    name: "Copenhagen Plank",
    category: "core",
    pattern: "iso_hold",
    level: 3,
    difficulty: 8,
    equipment: "none",
    unilateral: true,
    metric: "time_sec",
    defaultDose: [3, 3, 10, 30],
    cues: ["Side plank, top leg on a bench", "Bottom leg lifts to meet the bench underneath", "Time per side"],
  },
  {
    id: "core_windshield_wiper_floor",
    name: "Floor Windshield Wiper",
    category: "core",
    pattern: "anti_rotation",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 6, 14],
    cues: ["On your back, legs up at 90°", "Lower legs side to side — shoulders stay down", "Reps = total swings"],
  },
  {
    id: "core_ab_rollout_towel",
    name: "Towel Ab Rollout",
    category: "core",
    pattern: "anti_extension",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 5, 10],
    cues: ["Kneel, hands on a folded towel on a smooth floor", "Roll out — keep hips from sagging", "Pull back with abs, not arms"],
  },
  {
    id: "core_hanging_wiper",
    name: "Hanging Windshield Wiper",
    category: "core",
    pattern: "anti_rotation",
    level: 3,
    difficulty: 10,
    equipment: "bar",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 4, 8],
    cues: ["Legs up parallel to bar, controlled side-to-side", "No swinging the torso", "Reps = total swings"],
  },
];

// ---------------------------------------------------------------------------
// LEGS (14)
// ---------------------------------------------------------------------------

const LEGS: Exercise[] = [
  {
    id: "legs_bw_squat",
    name: "Bodyweight Squat",
    category: "legs",
    pattern: "squat",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 10, 20],
    cues: ["Feet shoulder-width, toes slightly out", "Hips back, knees track over toes", "Chest tall, full depth"],
  },
  {
    id: "legs_squat_pause",
    name: "Paused Squat",
    category: "legs",
    pattern: "squat",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    tempoHint: "3s pause at the bottom",
    cues: ["Sink to full depth, hold 3 seconds", "Knees stay tracking outward", "Drive up explosively"],
  },
  {
    id: "legs_reverse_lunge",
    name: "Reverse Lunge",
    category: "legs",
    pattern: "lunge",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Step back, drop back knee toward the floor", "Front shin near vertical", "Reps per leg"],
  },
  {
    id: "legs_forward_lunge",
    name: "Forward Lunge",
    category: "legs",
    pattern: "lunge",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Long step forward", "Both knees ~90°", "Drive through the front heel — reps per leg"],
  },
  {
    id: "legs_walking_lunge",
    name: "Walking Lunge",
    category: "legs",
    pattern: "lunge",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 10, 20],
    cues: ["Lunge forward, then bring the back leg through", "Stay tall — no leaning", "Reps = total steps"],
  },
  {
    id: "legs_step_up",
    name: "Step-Up",
    category: "legs",
    pattern: "lunge",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Use a knee-height surface", "Drive through the heel, don't push off the back foot", "Reps per leg"],
  },
  {
    id: "legs_bulgarian_split",
    name: "Bulgarian Split Squat",
    category: "legs",
    pattern: "lunge",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Rear foot on a bench", "Front shin near vertical at the bottom", "Reps per leg"],
  },
  {
    id: "legs_jump_squat",
    name: "Jump Squat",
    category: "legs",
    pattern: "plyo",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 8, 15],
    cues: ["Squat to parallel, explode up", "Land soft, immediately into the next rep", "Stay tall on take-off"],
  },
  {
    id: "legs_cossack",
    name: "Cossack Squat",
    category: "legs",
    pattern: "squat",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 5, 10],
    cues: ["Wide stance, shift weight side to side", "Working leg bends fully, other stays straight", "Reps per side"],
  },
  {
    id: "legs_shrimp_assist",
    name: "Assisted Shrimp Squat",
    category: "legs",
    pattern: "squat",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 3, 6],
    cues: ["Hold a support with one hand", "Free leg bent behind, knee taps the floor", "Reps per side"],
    scalingUp: "legs_shrimp",
  },
  {
    id: "legs_pistol_assist",
    name: "Assisted Pistol Squat",
    category: "legs",
    pattern: "squat",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 3, 8],
    cues: ["Hold a doorframe or pole for balance", "Free leg extended straight forward", "Reps per side"],
    scalingUp: "legs_pistol",
  },
  {
    id: "legs_pistol",
    name: "Pistol Squat",
    category: "legs",
    pattern: "squat",
    level: 3,
    difficulty: 9,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 2, 6],
    cues: ["Arms forward for counterbalance", "Sit back, free leg long and off the floor", "Reps per side"],
  },
  {
    id: "legs_shrimp",
    name: "Shrimp Squat",
    category: "legs",
    pattern: "squat",
    level: 3,
    difficulty: 9,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 2, 5],
    cues: ["Grab the rear foot behind you", "Knee taps the floor, drive back up", "Reps per side"],
  },
  {
    id: "legs_nordic_negative",
    name: "Nordic Curl Negative",
    category: "legs",
    pattern: "hinge",
    level: 3,
    difficulty: 9,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 3, 6],
    tempoHint: "Slow descent",
    cues: ["Kneel — anchor your ankles", "Lower forward in a straight line for as long as possible", "Catch with your hands"],
  },
  {
    id: "legs_glute_bridge",
    name: "Glute Bridge",
    category: "legs",
    pattern: "hinge",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 10, 20],
    cues: ["Heels close to glutes", "Drive hips to the ceiling", "Squeeze glutes hard at the top"],
  },
  {
    id: "legs_single_leg_bridge",
    name: "Single-Leg Glute Bridge",
    category: "legs",
    pattern: "hinge",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 6, 15],
    cues: ["One foot planted, other leg extended", "Hips lift level — no tilt", "Reps per side"],
  },
  {
    id: "legs_single_leg_rdl",
    name: "Single-Leg RDL",
    category: "legs",
    pattern: "hinge",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 6, 12],
    cues: ["Hinge at the hip, back leg extends behind", "Body forms a T at the bottom", "Reps per side"],
  },
  {
    id: "legs_calf_raise",
    name: "Standing Calf Raise",
    category: "legs",
    pattern: "hinge",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 12, 25],
    cues: ["Rise onto the balls of your feet", "Full lockout at the top — 1 second pause", "Lower slowly"],
  },
  {
    id: "legs_single_calf_raise",
    name: "Single-Leg Calf Raise",
    category: "legs",
    pattern: "hinge",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 8, 20],
    cues: ["Balance on one foot — hand on wall if needed", "Full range, slow lower", "Reps per side"],
  },
  {
    id: "legs_wall_sit",
    name: "Wall Sit",
    category: "legs",
    pattern: "iso_hold",
    level: 1,
    difficulty: 3,
    equipment: "wall",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 30, 75],
    cues: ["Back flat on the wall, knees at 90°", "Weight in the heels", "Breathe steady"],
  },
  {
    id: "legs_broad_jump",
    name: "Broad Jump",
    category: "legs",
    pattern: "plyo",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 4, 8],
    cues: ["Load hips, swing arms back", "Jump for maximum forward distance", "Stick the landing"],
  },
  {
    id: "legs_jumping_lunge",
    name: "Jumping Lunge",
    category: "legs",
    pattern: "plyo",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 8, 16],
    cues: ["Drop into a lunge, explode up, switch legs mid-air", "Land soft into the next rep", "Reps = total switches"],
  },
];

// ---------------------------------------------------------------------------
// CONDITIONING (9)
// ---------------------------------------------------------------------------

const CONDITIONING: Exercise[] = [
  {
    id: "cond_mountain_climbers",
    name: "Mountain Climbers",
    category: "conditioning",
    pattern: "locomotion",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 20, 45],
    cues: ["Plank position, drive knees to chest fast", "Hips low — don't pike", "Steady breathing"],
  },
  {
    id: "cond_high_knees",
    name: "High Knees",
    category: "conditioning",
    pattern: "locomotion",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 20, 45],
    cues: ["Run in place — knees to hip height", "Arms drive, posture tall", "Stay light on the balls of your feet"],
  },
  {
    id: "cond_jump_rope",
    name: "Jump Rope",
    category: "conditioning",
    pattern: "plyo",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 60, 180],
    cues: ["Small bounces — wrists do the work", "Elbows tucked, posture tall", "Skip the rope if you don't have one"],
  },
  {
    id: "cond_shadow_box",
    name: "Shadow Boxing",
    category: "conditioning",
    pattern: "locomotion",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 60, 180],
    cues: ["Light feet — jab, cross, slip", "Stay relaxed in the shoulders", "Breathe out on every punch"],
  },
  {
    id: "cond_burpee_no_push",
    name: "Burpee (No Push-Up)",
    category: "conditioning",
    pattern: "plyo",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [2, 4, 8, 15],
    cues: ["Drop to plank, jump feet back in", "Stand and reach overhead", "No push-up at the bottom"],
    scalingUp: "cond_burpee",
  },
  {
    id: "cond_burpee",
    name: "Burpee",
    category: "conditioning",
    pattern: "plyo",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [2, 4, 6, 15],
    cues: ["Drop, push-up, jump back in", "Explode up — clap overhead", "Land soft, reset"],
  },
  {
    id: "cond_squat_jumps_30",
    name: "Squat Jumps AMRAP",
    category: "conditioning",
    pattern: "plyo",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 20, 45],
    cues: ["Max reps in the time window", "Full depth on each squat", "Soft landings"],
  },
  {
    id: "cond_sprint_30",
    name: "30s Sprint",
    category: "conditioning",
    pattern: "locomotion",
    level: 2,
    difficulty: 6,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [3, 5, 30, 30],
    cues: ["All-out effort for 30 seconds", "Walk 60-90s between", "Hills boost the stimulus"],
  },
  {
    id: "cond_sprint_intervals",
    name: "10×100m Sprint Intervals",
    category: "conditioning",
    pattern: "locomotion",
    level: 3,
    difficulty: 9,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 1, 8, 12],
    cues: ["100m all-out, walk back as rest", "Drop a set if form breaks", "Pre-warm the hamstrings"],
  },
  {
    id: "cond_jumping_jacks",
    name: "Jumping Jacks",
    category: "conditioning",
    pattern: "locomotion",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 30, 90],
    cues: ["Light feet, full arm overhead reach", "Steady rhythm", "Land soft"],
  },
  {
    id: "cond_bear_crawl",
    name: "Bear Crawl",
    category: "conditioning",
    pattern: "locomotion",
    level: 1,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 20, 45],
    cues: ["Knees hover an inch off the floor", "Opposite hand + foot move together", "Hips low, core braced"],
  },
  {
    id: "cond_crab_walk",
    name: "Crab Walk",
    category: "conditioning",
    pattern: "locomotion",
    level: 1,
    difficulty: 3,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [2, 3, 20, 45],
    cues: ["Sit, hands behind you, hips up", "Walk forward + backward in tabletop", "Don't let hips drop"],
  },
  {
    id: "cond_lateral_bounds",
    name: "Lateral Bounds",
    category: "conditioning",
    pattern: "plyo",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 8, 20],
    cues: ["Push off one leg, land soft on the other", "Stick the landing for a beat", "Reps = total bounds"],
  },
  {
    id: "cond_tuck_jumps",
    name: "Tuck Jumps",
    category: "conditioning",
    pattern: "plyo",
    level: 2,
    difficulty: 7,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [3, 4, 5, 12],
    cues: ["Jump high, knees to chest at peak", "Soft landings", "Reset between reps"],
  },
  {
    id: "cond_skater_jumps",
    name: "Skater Jumps",
    category: "conditioning",
    pattern: "plyo",
    level: 2,
    difficulty: 5,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [3, 4, 10, 20],
    cues: ["Bound side to side, free leg crosses behind", "Land soft, immediately push off", "Reps = total bounds"],
  },
  {
    id: "cond_hill_sprint",
    name: "Hill Sprint",
    category: "conditioning",
    pattern: "locomotion",
    level: 3,
    difficulty: 9,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 1, 5, 10],
    cues: ["20-40m moderate-steep hill, all-out up", "Walk down to recover", "Reps = total sprints"],
  },
];

// ---------------------------------------------------------------------------
// MOBILITY (6)
// ---------------------------------------------------------------------------

const MOBILITY: Exercise[] = [
  {
    id: "mob_world_greatest",
    name: "World's Greatest Stretch",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [1, 2, 4, 8],
    cues: ["Lunge → hand to opposite ankle → open up to the ceiling", "Slow and deliberate", "Reps per side"],
  },
  {
    id: "mob_cat_cow",
    name: "Cat-Cow",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 1,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 2, 6, 12],
    cues: ["Quadruped — flex and extend the spine", "Move with breath", "Full range, no force"],
  },
  {
    id: "mob_scap_pulls",
    name: "Scapular Pulls",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 2,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 3, 5, 10],
    cues: ["Dead hang", "Pull shoulder blades down without bending elbows", "Pause at the top"],
  },
  {
    id: "mob_shoulder_dislocates",
    name: "Shoulder Dislocates",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 2, 8, 12],
    cues: ["Use a band, towel, or stick — wide grip", "Pass overhead and behind, slow and controlled", "Narrow the grip as it loosens"],
  },
  {
    id: "mob_hip_90_90",
    name: "Hip 90/90",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: true,
    metric: "time_sec",
    defaultDose: [1, 2, 20, 40],
    cues: ["Front + back leg both at 90°", "Sit tall, lean over the front shin", "Time per side"],
  },
  {
    id: "mob_dead_hang",
    name: "Dead Hang",
    category: "mobility",
    pattern: "iso_hold",
    level: 1,
    difficulty: 3,
    equipment: "bar",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [1, 3, 20, 60],
    cues: ["Hang from the bar, arms straight", "Relax shoulders — let the lats stretch", "Build up gradually"],
  },
  {
    id: "mob_thoracic_opener",
    name: "Thoracic Opener (Quadruped)",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 1,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [1, 2, 6, 10],
    cues: ["Quadruped — one hand behind the head", "Rotate elbow up to the ceiling, then under", "Reps per side"],
  },
  {
    id: "mob_couch_stretch",
    name: "Couch Stretch",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 3,
    equipment: "wall",
    unilateral: true,
    metric: "time_sec",
    defaultDose: [1, 2, 30, 60],
    cues: ["Back foot up on a wall, front foot flat", "Squeeze glute on the rear leg", "Tall torso — time per side"],
  },
  {
    id: "mob_pigeon",
    name: "Pigeon Stretch",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 2,
    equipment: "none",
    unilateral: true,
    metric: "time_sec",
    defaultDose: [1, 2, 30, 60],
    cues: ["Front shin angled across, back leg extended", "Sink the hips, fold forward", "Time per side"],
  },
  {
    id: "mob_ankle_rocks",
    name: "Half-Kneeling Ankle Rocks",
    category: "mobility",
    pattern: "stretch",
    level: 1,
    difficulty: 1,
    equipment: "none",
    unilateral: true,
    metric: "reps",
    defaultDose: [1, 2, 6, 12],
    cues: ["Half-kneeling — front knee drives past the toes", "Heel stays down", "Reps per side"],
  },
  {
    id: "mob_jefferson_curl",
    name: "Jefferson Curl (Bodyweight)",
    category: "mobility",
    pattern: "stretch",
    level: 2,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 2, 4, 8],
    cues: ["Slow segmental flexion — chin to chest first", "Roll down vertebra by vertebra", "Reverse just as slowly"],
  },
  {
    id: "mob_pancake",
    name: "Pancake Stretch",
    category: "mobility",
    pattern: "stretch",
    level: 2,
    difficulty: 4,
    equipment: "none",
    unilateral: false,
    metric: "time_sec",
    defaultDose: [1, 2, 30, 60],
    cues: ["Seated, legs wide", "Hinge from hips, chest forward — not collapsed", "Breathe into the stretch"],
  },
  {
    id: "mob_german_hang_negative",
    name: "German Hang Negative",
    category: "mobility",
    pattern: "stretch",
    level: 3,
    difficulty: 7,
    equipment: "bar",
    unilateral: false,
    metric: "reps",
    defaultDose: [1, 3, 3, 6],
    tempoHint: "Slow + controlled",
    cues: ["From a skin-the-cat, lower into a back-extended hang", "Only as far as shoulder mobility allows", "Bail with a tuck if needed"],
  },
];

// ---------------------------------------------------------------------------
// Aggregate + lookup helpers
// ---------------------------------------------------------------------------

export const EXERCISES: ReadonlyArray<Exercise> = Object.freeze([
  ...PUSH,
  ...PULL,
  ...CORE,
  ...LEGS,
  ...CONDITIONING,
  ...MOBILITY,
]);

// Build an id → exercise lookup once at module load.
const EXERCISE_BY_ID: ReadonlyMap<string, Exercise> = (() => {
  const m = new Map<string, Exercise>();
  const dupes: string[] = [];
  for (const ex of EXERCISES) {
    if (m.has(ex.id)) dupes.push(ex.id);
    m.set(ex.id, ex);
  }
  if (dupes.length > 0) {
    // This is a developer error — fail loudly so it's caught at deploy time.
    throw new Error(`[CALI-LIB] Duplicate exercise ids: ${dupes.join(", ")}`);
  }
  return m;
})();

console.log(
  `[CALI-LIB] Loaded ${EXERCISES.length} exercises (${LIBRARY_VERSION}) — ` +
    `push:${PUSH.length} pull:${PULL.length} core:${CORE.length} ` +
    `legs:${LEGS.length} cond:${CONDITIONING.length} mob:${MOBILITY.length}`,
);

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_BY_ID.get(id);
}

export function exercisesByCategory(cat: CaliCategory): Exercise[] {
  return EXERCISES.filter((e) => e.category === cat);
}
