/**
 * BOTB Scaling Infrastructure
 * ============================
 * Handles the high-severity scaling bottlenecks for 5K–250K user load.
 *
 * PROBLEMS SOLVED:
 *   1. Battle Mutex       — Prevents read-modify-write race conditions on
 *                           concurrent vote tallying by serializing writes per battle.
 *   2. Response Cache     — TTL-based in-memory cache for expensive aggregate
 *                           queries (voter leaderboard, athlete leaderboard).
 *   3. Wallet Vote Index  — Maintains `wvote:{wallet}:{battleId}` keys so
 *                           "my votes" queries hit O(user's votes) not O(all votes).
 *   4. Allocation Index   — Maintains `walloc:{wallet}:{eventId}` aggregate so
 *                           event-scoped balance checks are O(1) not O(battles).
 *   5. Nonce Reaper       — Lazily cleans expired vote-nonce keys to prevent
 *                           unbounded key accumulation.
 *
 * DESIGN CONSTRAINTS:
 *   - Cannot modify kv_store.tsx (protected autogenerated file)
 *   - KV only supports: get, set, del, mget, mset, mdel, getByPrefix
 *   - getByPrefix returns values only (not keys)
 *   - All indices must be maintained at write time (no background workers)
 *   - Deno is single-threaded but async — interleaving is the race vector
 */

import * as kv from "./kv_store.tsx";

// ===========================================================================
// 1. BATTLE MUTEX — Async lock per battle ID
// ===========================================================================
// Deno's single thread can still interleave async I/O. Two concurrent votes
// on the same battle: both read tallies → both increment → both write →
// one increment is lost. This mutex serializes the critical section.
//
// Scope: in-memory (single edge function instance). Supabase Edge Functions
// run per-request in isolated workers in prod, but during sustained traffic
// multiple requests CAN overlap on the same worker. The mutex handles that.
// If separate workers process the same battle, the winner-declaration
// recalc (line 1352 in index.tsx) corrects any drift at snapshot time.
// ---------------------------------------------------------------------------

const battleLocks = new Map<string, Promise<void>>();

/**
 * Acquire an exclusive async lock for a given key (typically `battle:{id}`).
 * Returns a release function that MUST be called in a finally block.
 *
 * Usage:
 *   const release = await acquireLock(`battle:${battleId}`);
 *   try { ... critical section ... } finally { release(); }
 */
export async function acquireLock(key: string): Promise<() => void> {
  // Wait for any existing lock on this key
  while (battleLocks.has(key)) {
    await battleLocks.get(key);
  }

  // Create a new lock and store it
  let releaseFn!: () => void;
  const lockPromise = new Promise<void>((resolve) => {
    releaseFn = resolve;
  });
  battleLocks.set(key, lockPromise);

  return () => {
    battleLocks.delete(key);
    releaseFn();
  };
}

// ===========================================================================
// 2. RESPONSE CACHE — TTL-based in-memory cache
// ===========================================================================
// Used for expensive aggregate queries that don't need real-time accuracy.
// Voter leaderboard, athlete leaderboard, etc. can tolerate 30-60s staleness.
// ---------------------------------------------------------------------------

interface CacheEntry<T> {
  data: T;
  expiresAt: number;
}

const memCache = new Map<string, CacheEntry<any>>();

/**
 * Get a cached value, or compute + cache it if expired/missing.
 * @param key    Cache key (e.g. "leaderboard:voters")
 * @param ttlMs  Time-to-live in milliseconds
 * @param compute  Async function to compute the value on miss
 */
export async function cached<T>(
  key: string,
  ttlMs: number,
  compute: () => Promise<T>,
): Promise<T> {
  const entry = memCache.get(key);
  if (entry && Date.now() < entry.expiresAt) {
    return entry.data;
  }

  const data = await compute();
  memCache.set(key, { data, expiresAt: Date.now() + ttlMs });
  return data;
}

/**
 * Invalidate a specific cache key (e.g. after a vote is cast).
 */
export function invalidateCache(key: string): void {
  memCache.delete(key);
}

/**
 * Invalidate all cache keys matching a prefix.
 */
export function invalidateCacheByPrefix(prefix: string): void {
  for (const key of memCache.keys()) {
    if (key.startsWith(prefix)) memCache.delete(key);
  }
}

// ===========================================================================
// 3. WALLET VOTE INDEX — Per-wallet vote lookups
// ===========================================================================
// Key pattern: wvote:{wallet}:{battleId} → compact vote summary
//
// Replaces the full-table-scan pattern:
//   OLD: getByPrefix("vote:battle:") → filter by wallet  [O(ALL votes)]
//   NEW: getByPrefix("wvote:{wallet}:")                   [O(user's votes)]
//
// At 50K users with avg 10 votes each:
//   OLD: 500K rows transferred per request
//   NEW: ~10 rows transferred per request
// ---------------------------------------------------------------------------

export interface CompactVote {
  battleId: string;
  athleteId: string;
  eventId: string;
  stakeAmount: number;
  weightedVote: number;
  votingPower: number;
  hasGovernorNFT: boolean;
  hasSigmaNFT: boolean;
  isUpdate: boolean;
  timestamp: string;
  wallet: string;
}

/**
 * Write the wallet vote index entry for a cast vote.
 */
export async function indexWalletVote(vote: CompactVote): Promise<void> {
  await kv.set(`wvote:${vote.wallet}:${vote.battleId}`, vote);
}

/**
 * Read all votes for a specific wallet via the index.
 * Returns compact vote summaries (no signatures/nonces).
 */
export async function getWalletVotes(wallet: string): Promise<CompactVote[]> {
  return await kv.getByPrefix(`wvote:${wallet}:`);
}

/**
 * Delete a wallet vote index entry (used by battle clear).
 */
export async function deleteWalletVote(wallet: string, battleId: string): Promise<void> {
  await kv.del(`wvote:${wallet}:${battleId}`);
}

// ===========================================================================
// 4. ALLOCATION INDEX — Per-wallet per-event token allocation
// ===========================================================================
// Key pattern: walloc:{wallet}:{eventId} → { totalAllocated, battles: { [bid]: amount } }
//
// Replaces the O(battles × KV reads) pattern in POST /vote/battle:
//   OLD: getByPrefix("battle:") → filter by event → kv.get per battle  [O(N reads)]
//   NEW: kv.get("walloc:{wallet}:{eventId}")                           [O(1 read)]
//
// At 50 battles per event:
//   OLD: 50 sequential KV reads per vote cast
//   NEW: 1 KV read per vote cast
// ---------------------------------------------------------------------------

export interface AllocationIndex {
  wallet: string;
  eventId: string;
  totalAllocated: number;
  battles: Record<string, number>; // battleId → stakeAmount
}

/**
 * Get current allocation for a wallet in an event. Returns null if no votes yet.
 */
export async function getAllocation(
  wallet: string,
  eventId: string,
): Promise<AllocationIndex | null> {
  return await kv.get(`walloc:${wallet}:${eventId}`);
}

/**
 * Update allocation when a vote is cast/updated.
 * @param wallet     Voter wallet
 * @param eventId    Event the battle belongs to
 * @param battleId   Battle being voted on
 * @param newStake   New stake amount for this battle
 * @param oldStake   Previous stake (0 if new vote)
 */
export async function updateAllocation(
  wallet: string,
  eventId: string,
  battleId: string,
  newStake: number,
  oldStake: number,
): Promise<void> {
  const key = `walloc:${wallet}:${eventId}`;
  let alloc: AllocationIndex = await kv.get(key) || {
    wallet,
    eventId,
    totalAllocated: 0,
    battles: {},
  };

  // Remove old stake for this battle if it existed
  const previousStake = alloc.battles[battleId] || 0;
  alloc.totalAllocated -= previousStake;

  // Add new stake
  alloc.battles[battleId] = newStake;
  alloc.totalAllocated += newStake;

  await kv.set(key, alloc);
}

/**
 * Remove a battle's stake from a wallet's allocation (used by battle clear).
 */
export async function removeAllocationBattle(
  wallet: string,
  eventId: string,
  battleId: string,
): Promise<void> {
  const key = `walloc:${wallet}:${eventId}`;
  const alloc: AllocationIndex | null = await kv.get(key);
  if (!alloc) return;

  const removedStake = alloc.battles[battleId] || 0;
  delete alloc.battles[battleId];
  alloc.totalAllocated = Math.max(0, alloc.totalAllocated - removedStake);

  // Clean up if no more battles in this event allocation
  if (Object.keys(alloc.battles).length === 0) {
    await kv.del(key);
  } else {
    await kv.set(key, alloc);
  }
}

/**
 * Get all event allocations for a wallet (for the allocations endpoint).
 */
export async function getWalletAllocations(
  wallet: string,
): Promise<AllocationIndex[]> {
  return await kv.getByPrefix(`walloc:${wallet}:`);
}

// ===========================================================================
// 5. NONCE REAPER — Lazy cleanup of expired vote nonces
// ===========================================================================
// Problem: Every vote writes `vote-nonce:{nonce}` that's never deleted.
//          At 500K votes, that's 500K zombie keys.
//
// Solution: Store nonce with timestamp. On every Nth vote, scan and delete
//           nonces older than 24 hours. "Lazy reaping" — no background job needed.
// ---------------------------------------------------------------------------

const NONCE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours
const REAP_INTERVAL = 50; // Reap every 50th vote
let voteCounter = 0;

/**
 * Write a nonce with timestamp and self-referencing key for replay
 * protection and lazy reaper cleanup. The `_nonceKey` field lets
 * the reaper reconstruct the full KV key from the value alone
 * (getByPrefix returns values only, not keys).
 */
export async function writeNonceWithKey(
  nonce: string,
  wallet: string,
  battleId: string,
): Promise<void> {
  await kv.set(`vote-nonce:${nonce}`, {
    used: true,
    _nonceKey: nonce, // Self-referencing key for reaper reconstruction
    wallet,
    battleId,
    timestamp: new Date().toISOString(),
    expiresAt: Date.now() + NONCE_TTL_MS,
  });

  // Lazy reap on every Nth vote
  voteCounter++;
  if (voteCounter >= REAP_INTERVAL) {
    voteCounter = 0;
    reapExpiredNonces().catch((err) => {
      console.log(`[SCALING] Nonce reap error (non-fatal): ${err}`);
    });
  }
}

/**
 * Reap expired nonce keys. Runs in background, non-blocking.
 * Deletes up to 200 expired nonces per run to avoid long operations.
 */
async function reapExpiredNonces(): Promise<void> {
  const allNonces: any[] = await kv.getByPrefix("vote-nonce:");
  const now = Date.now();
  const expiredKeys: string[] = [];

  for (const n of allNonces) {
    // Old nonces without expiresAt are cleaned after 24h from timestamp
    const expiry = n.expiresAt || (n.timestamp ? new Date(n.timestamp).getTime() + NONCE_TTL_MS : 0);
    if (expiry > 0 && now > expiry) {
      // We need to reconstruct the key — nonce value is stored in the object
      // Since getByPrefix strips keys, we need the nonce field from the value
      // Old format stored the nonce in the key pattern, not the value.
      // For safety, we'll skip items where we can't identify the original nonce.
      // New nonces are written with the nonce in the signedMessage or as part of battleId context.
      // Actually, the key IS `vote-nonce:{nonce}` and the value has no direct nonce field.
      // We need a different approach: store the nonce string in the value itself.
      if (n._nonceKey) {
        expiredKeys.push(`vote-nonce:${n._nonceKey}`);
      }
    }
    if (expiredKeys.length >= 200) break;
  }

  if (expiredKeys.length > 0) {
    await kv.mdel(expiredKeys);
    console.log(`[SCALING] Reaped ${expiredKeys.length} expired nonce keys.`);
  }
}

// ===========================================================================
// 6. INDEX MIGRATION HELPER — Backfill indices from existing data
// ===========================================================================
// On first request after deployment, old votes won't have wvote/walloc indices.
// This helper detects the gap and backfills. Runs once, then sets a flag.
// ---------------------------------------------------------------------------

let migrationChecked = false;

/**
 * One-time migration: backfill wallet vote index + allocation index
 * from existing `vote:battle:*` records.
 * Safe to call repeatedly — only runs once per server lifecycle.
 */
export async function ensureIndicesMigrated(): Promise<void> {
  if (migrationChecked) return;
  migrationChecked = true;

  const migrationFlag = await kv.get("_migration:scaling-indices-v1");
  if (migrationFlag) return; // Already migrated

  console.log("[SCALING] Starting one-time index migration...");
  const startTime = Date.now();

  try {
    const allVotes: any[] = await kv.getByPrefix("vote:battle:");
    if (allVotes.length === 0) {
      await kv.set("_migration:scaling-indices-v1", { migratedAt: new Date().toISOString(), voteCount: 0 });
      console.log("[SCALING] No existing votes — migration complete (no-op).");
      return;
    }

    // Batch write wallet vote indices
    const wvoteKeys: string[] = [];
    const wvoteVals: any[] = [];
    // Accumulate allocation data
    const allocMap = new Map<string, AllocationIndex>();

    for (const v of allVotes) {
      if (!v.wallet || !v.battleId) continue;

      // Wallet vote index
      wvoteKeys.push(`wvote:${v.wallet}:${v.battleId}`);
      wvoteVals.push({
        battleId: v.battleId,
        athleteId: v.athleteId,
        eventId: v.eventId || "standalone",
        stakeAmount: v.stakeAmount || 0,
        weightedVote: v.weightedVote || 0,
        votingPower: v.votingPower || 1,
        hasGovernorNFT: v.hasGovernorNFT || false,
        hasSigmaNFT: v.hasSigmaNFT || false,
        isUpdate: v.isUpdate || false,
        timestamp: v.timestamp || "",
        wallet: v.wallet,
      });

      // Allocation index
      const eventId = v.eventId || "standalone";
      const allocKey = `${v.wallet}:${eventId}`;
      let alloc = allocMap.get(allocKey);
      if (!alloc) {
        alloc = { wallet: v.wallet, eventId, totalAllocated: 0, battles: {} };
        allocMap.set(allocKey, alloc);
      }
      alloc.battles[v.battleId] = v.stakeAmount || 0;
      alloc.totalAllocated += v.stakeAmount || 0;
    }

    // Write wallet vote indices in batches of 50
    for (let i = 0; i < wvoteKeys.length; i += 50) {
      await kv.mset(
        wvoteKeys.slice(i, i + 50),
        wvoteVals.slice(i, i + 50),
      );
    }

    // Write allocation indices
    const allocKeys: string[] = [];
    const allocVals: any[] = [];
    for (const [key, val] of allocMap.entries()) {
      const [wallet, eventId] = key.split(":");
      allocKeys.push(`walloc:${wallet}:${eventId}`);
      allocVals.push(val);
    }
    for (let i = 0; i < allocKeys.length; i += 50) {
      await kv.mset(
        allocKeys.slice(i, i + 50),
        allocVals.slice(i, i + 50),
      );
    }

    const elapsed = Date.now() - startTime;
    await kv.set("_migration:scaling-indices-v1", {
      migratedAt: new Date().toISOString(),
      voteCount: allVotes.length,
      walletIndices: wvoteKeys.length,
      allocationIndices: allocKeys.length,
      elapsedMs: elapsed,
    });

    console.log(`[SCALING] Migration complete: ${wvoteKeys.length} wallet vote indices + ${allocKeys.length} allocation indices created in ${elapsed}ms.`);
  } catch (err) {
    console.log(`[SCALING] Migration error (will retry on next request): ${err}`);
    migrationChecked = false; // Allow retry
  }
}